apiVersion: v1
kind: Pod
metadata:
  name: node-teste
spec:
  containers:
  - name: node-teste-container
    image: phillrog/teste-node:latest
    imagePullPolicy: Always
  imagePullSecrets:
  - name: docker-cfg