name: Teste Deploy Imagem Docker
 
on:
  push:
    branches: [ "main" ]
env:
  USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
  
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        run: |
            docker login -u ${{ env.USERNAME }} -p ${{ env.PASSWORD }}

       
