name: Teste Deploy Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs: 

  build:

    runs-on: ubuntu-latest

    steps:
      -
        name: Login no Docker Hub
        uses: docker/login-action@v3
        env:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_PASSWORD}}
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
