name: Teste Deploy Imagem Docker

on:
  push:
    branches: [ "main" ]

jobs: 

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login 
        id: docker-hub
        run: |
            docker login --username ${{secrets.DOCKERHUB_USERNAME}} --password ${{secrets.DOCKERHUB_PASSWORD}}
      
