name: Teste Deploy Imagem Docker
 
on:
  push:
    branches: [ "main" ]
 
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
       - uses: docker/login-action@v1
       - name: Login to DockerHub Registry
         with:
              registry: https://index.docker.io/v1/
              username: ${{ secrets.DOCKERHUB_USERNAME  }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }} 
 
       
